name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar .NET SDK 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar Dependências
      run: dotnet restore src/UnitTestingTutorial.slnx

    - name: Compilar
      run: dotnet build src/UnitTestingTutorial.slnx --no-restore -c Release

    - name: Executar Testes com Cobertura
      run: >
        dotnet test src/UnitTestingTutorial.slnx 
        --no-build 
        -c Release 
        --collect:"XPlat Code Coverage"

    - name: Upload da Cobertura de Código como Artefato
      uses: actions/upload-artifact@v4
      with:
        name: cobertura-cobertura-xml
        path: "**/TestResults/**/coverage.cobertura.xml"